import Head from "next/head";
import { useEffect, useState } from "react";

import { loginWithGithub, onAuthStateChanged } from "firebase/client";

import styles from "styles/style.module.scss";

import AppButton from "components/AppButton";
import AppLayout from "components/AppLayout";
import Github from "components/Icons/Github";
import Avatar from "components/Avatar";

export default function Home() {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    onAuthStateChanged((user) => setUser(user));
  }, []);

  const handleClick = () => {
    loginWithGithub()
      .then((user) => {
        const { avatar, username, url } = user;
        setUser(user);
        console.log(user);
      })
      .catch((err) => console.log(err));
  };

  return (
    <div>
      <Head>
        <title>Dev's social ☕️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section className={styles.section}>
          <img className={styles.image} src="/logo.png" />
          <h1 className={styles.h1}>Dev's social media</h1>
          <h2 className={styles.h2}>Talk about code with developers</h2>
          <div className={styles.btnContainer}>
            {user === null && (
              <AppButton onClick={handleClick}>
                <Github width={24} height={24} />
                Log in with Github
              </AppButton>
            )}
            {user && user.avatar && (
              <div>
                <Avatar
                  avatar={user.avatar}
                  alt={user.username}
                  text={user.username}
                />
              </div>
            )}
          </div>
        </section>
      </AppLayout>
    </div>
  );
}
